# Generated by Django 3.0.7 on 2020-06-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('discount_value', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
